### PR TITLE
remove some legacy code

### LINKED ISSUE #27: remove graphfamous?
I don't think a plotting package is the right place for this
https://github.com/JuliaGraphs/GraphPlot.jl/blob/master/src/graphio.jl

Maybe move it to LighGraphs? @sbromberger @afternone 

Both the functions `graphfamous` and `readedgelist` should be removed

### PR DESCRIPTION
**Pull request by CarloLucibello**
removing a bunch of lines of unneeded code (precompiles and duplicated code), as @afternone should confirm

also fixes #27 , moving the graphfamous function and the data collection in the `deprecated/` directory, waiting for a definitive collocation somewhere else (LightGraphs?)

### CODE REVIEW

**Comment by CarloLucibello** [comment]
@afternone this should be ready to merge. Please take a look and merge if you feel confortable with it

**Comment by juliohm** [comment]
Is this PR still valid? @afternone, are you fine with @sbromberger merging PRs? It seems that you are quite busy lately...

**Comment by sbromberger** [comment]
This PR has merge conflicts and cannot be merged now. I recommend either resolving the conflicts here or creating a new PR.

**Comment by juliohm** [comment]
Can we just close this? Given the time since this PR was opened, it will probably be easier to start a new PR with the latest master.

**Comment by juliohm** [comment]
It now has conflicts with the latest visual tests, and it still using FactCheck.jl that we dropped sometime ago. Plus, we have deleted some files that were obsolete (and repeated) in the project as well. I am not sure we can reuse this PR as of now.

**Pull request closed without merging**
