### PR TITLE
added project toml

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Comment by simonschoelly** [comment]
If this is a problem with the `.travis` file, maybe we should copy what we have in LightGraphs

**Comment by matbesancon** [comment]
I fixed it this should do

**Comment by simonschoelly** [comment]
Still not working, maybe we remove the part in `script:` from travis, then the default script should get used.

**Comment by simonschoelly** [comment]
Should we add a `[compat]` section? We have some requirements in `REQUIREMENTS`, so maybe we should also have them here.

See https://julialang.github.io/Pkg.jl/dev/compatibility/

**Comment by matbesancon** [comment]
yup good point

**Comment by simonschoelly** [comment]
Now we have to figure out how to tell Registrator.

**Pull request merged**
