### PR TITLE
bump version for new Compose compat

### PR DESCRIPTION
**Pull request by KristofferC**
Would be nice with a new release with this

### CODE REVIEW

**Comment by matbesancon** [comment]
pinging @simonschoelly 
Also @KristofferC travis seems to error here

**Comment by DilumAluthge** [comment]
@KristofferC can you close and reopen this pull request? That should re-trigger Travis.

**Comment by sbromberger** [comment]
I can do it.

**Comment by simonschoelly** [comment]
Passed on travis, so I merged it now. Sorry for being so slow, I don't find much time for open source things these days.

**Pull request merged**
