### PR TITLE
Remove Graphs.jl dependency

### PR DESCRIPTION
**Pull request by sbromberger**
@juliohm and  @afternone - could you please review this (ref: #19) ? Thank you.

### CODE REVIEW

**Comment by juliohm** [comment]
I only had the chance to skim over the modified *.jl files, they all look great!

My vote is for merging.

**Comment by sbromberger** [comment]
@afternone - can we get this merged? We need to do some fixes for 0.6, but I'd like to merge this first. Thanks.

**Comment by juliohm** [comment]
Also, please consider giving Seth write privilegies :)

**Comment by sbromberger** [comment]
For the record, I have write privs as the owner of JuliaGraphs. I'm just not really comfortable 1) merging my own PRs in 2) someone else's repo. :)

**Comment by juliohm** [comment]
Makes total sense :)

**Comment by afternone** [comment]
It's ready to merge.  Recently, I'm busy preparing my doctoral dissertation and thesis defense.  After that I will do some fixes for 0.6.

**Comment by sbromberger** [comment]
@afternone GOOD LUCK! Do you mind if I merge this then (and perhaps do some small stuff while you're busy)?

**Comment by afternone** [comment]
It's ok!

**Comment by sbromberger** [comment]
Thanks. Merging this now.

**Pull request merged**
