### PR TITLE
Create REQUIRE

### PR DESCRIPTION
**Pull request by sbromberger**
added FactCheck to test dependencies

### CODE REVIEW

**Comment by sbromberger** [comment]
So, I'll be doing my best to make sure this passes tests, but would you consider moving from FactCheck to Base.Test?

**Comment by sbromberger** [comment]
PS: my general policy is that I won't merge my own PRs on packages I'm not primary author on unless there's some sort of emergency (I made an exception in #16 to kick off travis testing). Therefore, merging this one's up to you, @afternone :)

**Comment by afternone** [comment]
Thanks for your work. Recently, I am busy writing my doctoral thesis, thus have little time to fix the problem of this package.

**Comment by sbromberger** [comment]
I'm happy to help. Thanks for moving it under JuliaGraphs. It's a nice addition to our organization.

**Pull request merged**
