### PR TITLE
Allow edge label offset for undirected graphs

### LINKED ISSUE #23: Directed Graphs edgelabels fix?
This [commit](https://github.com/JuliaGraphs/GraphPlot.jl/commit/ab1b9444e056a6e9d87b9b91617ee8e99eda08e1) modified the placement of edge labels for directed graphs such that the edge label location cannot be altered by the end user.  Can this change be reverted such as to allow for the placement of edge labels to still be controlled by the `edgelabeldistx` and `edgelabeldisty` arguments?

### PR DESCRIPTION
**Pull request by juliohm**
Fix #23. @sbromberger could you please review and merge? This can also be included before the new tag.

### CODE REVIEW

**Comment by sbromberger** [comment]
I don't really know how to review this since I don't understand the layout code. @juliohm - if you confirm it works as expected, I'll go ahead and merge.

**Comment by juliohm** [comment]
The code is very simple @sbromberger , if the graph is undirected we place the label of the edge in the midpoint of the edge, if the graph is directed we shift the midpoint towards the end of the edge, that is, we take the average of midpoint and tail. In both cases, we also allow the user to provide an offset. Introducing parentheses will make the offset option hold for both cases.

We shouldn't have any problems by merging this and including it in the new tag.

**Comment by sbromberger** [comment]
Sounds good to me :)

**Comment by sbromberger** [comment]
Will tag a new version now.

**Pull request merged**
