### PR TITLE
Rename chksquare to checksquare

### PR DESCRIPTION
**Pull request by juliohm**
In the face of https://github.com/JuliaLang/julia/pull/14601

### CODE REVIEW

**Comment by juliohm** [comment]
The build is passing in Julia v0.5, should this be merged?

**Comment by juliohm** [comment]
Could someone please merge this? We need another PR to fix the build failure in Julia v0.6, it is unrelated.

**Comment by sbromberger** [comment]
I can merge.

**Comment by sbromberger** [comment]
Can you fix the 0.6 tests?

**Comment by juliohm** [comment]
Thank you :blush:

**Pull request merged**
