### PR TITLE
Update plot.jl to account for line style

### LINKED ISSUE #127: Dashed edges?
Hello, 

I am using graph plot and it would be interesting to add the feature of changing the style of the edge line.
In my application having the possibility to set a dashed line would be significantly helpful.
Have you considered the option?

Thank you,
Davide

### PR DESCRIPTION
**Pull request by davide-f**
Hi,

This commit resolves #127 

Regards,
Davide

### CODE REVIEW

**Comment by davide-f** [comment]
It seems like there are some pull requests pending; do you see that they will be investigated and completed in the foreseable future?
Thank you,
Davide

**Comment by hdavid16** [comment]
@simonschoelly, did this PR fall through the cracks?

**Comment by etiennedeg** [comment]
oops, I messed something up...

**Comment by etiennedeg** [comment]
I tried to rebase the PR and add a commit withsome documentation about it, but that didn't worked as expected. Maybe I should try reopening a PR.

**Comment by etiennedeg** [comment]
Ok, I think I understand what happened: the PR was on master, and I already add a master branch created. so when I fetched it, it renamed the branch, and when I pushed, it pushed my master instead of the modifications. Sorry about that, I will make a new PR.

**Comment by etiennedeg** [comment]
new PR: #176

**Comment by simonschoelly** [comment]
`git rebase -i` + force push afterwards might help in such situtations

**Comment by etiennedeg** [comment]
I think this is what I did, but I pushed the master instead of the PR branch

**Pull request closed without merging**
