### PR TITLE
use @__DIR__ instead of Pkg.dir

### PR DESCRIPTION
**Pull request by tkelman**
this allows installing and loading the package from elsewhere

### CODE REVIEW

**Comment by sbromberger** [comment]
Thanks, @tkelman. Just curious - does this apply to `.travis.yml` as well?

**Comment by tkelman** [comment]
Nah, Pkg.dir is fine in .travis.yml

**Comment by sbromberger** [comment]
I'm going to merge this - the OSX tests are taking > 20 mins to run, but it's passed the Linux tests.

**Comment by sbromberger** [comment]
@tkelman do you recommend pulling the METADATA PR and resubmitting with these changes, or can it wait until our next version?

**Comment by tkelman** [comment]
this is more correct, and attobot will update the existing PR in place if you replace the release, but whichever you prefer

**Comment by sbromberger** [comment]
Let me see how to replace the release.

**Comment by sbromberger** [comment]
Done: https://github.com/JuliaLang/METADATA.jl/pull/9969

**Comment by tkelman** [comment]
looks like you got it, but there are instructions on the attobot readme just in case

**Comment by sbromberger** [comment]
Thanks :)

**Pull request merged**
