### PR TITLE
make default spring_layout deterministic

### LINKED ISSUE #76: make default layout deterministic
The default `spring_layout` is non-deterministic, which doesn't seem desirable to me.  It seems better to do something like:

```jl
function deterministic_spring_layout(g::AbstractGraph; seed::Integer=0, kws...)
    rng = MersenneTwister(seed)
    spring_layout(g, 2 .* rand(rng, nv(g)) .- 1.0, 2 .* rand(rng,nv(g)) .- 1.0; kws...)
end
```

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #76.

### CODE REVIEW

**Comment by simonschoelly** [comment]
At a quick glance, there seem to be two problems here:
1. `MersenneTwister` was moved to `Random`, so you might have to add a `using Random` or `using Random: MersenneTwister`

2. GraphPlot has visual regression tests, i.e it has stored some pictures of previous outputs and compares the new output to them. As you seem to have changed how random seeds work, the output is also different.
Does this error also appear when you test locally on your computer?

**Comment by stevengj** [comment]
Yes, I guess I'll need to update the tests.

**Comment by stevengj** [comment]
CI is green.

**Comment by stevengj** [comment]
Bump.

**Comment by simonschoelly** [comment]
Sorry for the huge delay and thanks for your work.

**Pull request merged**
