### PR TITLE
Request Compose compat to include 0.8 please

### PR DESCRIPTION
**Pull request by dehann**
Gadfly.jl now uses the much improved Compose.jl v0.8 and cross dependencies are a little tricky.

### CODE REVIEW

**Comment by matbesancon** [comment]
Wasn't the 0.7 -> 0.8 breaking? Could you check that everything works fine on both versions? Otherwise we can drop 0.7

**Comment by simonschoelly** [comment]
I could not check everything, but at least the example notebook works perfectly fine with this pr. In addition we have a few visual regression test and these also seem to pass.

**Comment by KristofferC** [comment]
Bump, could this please be merged (seems tests still pass nicely).

**Comment by matbesancon** [comment]
@simonschoelly I'd be for merging this too and fixing bugs if people are still on Compose 0.7 and report them

**Comment by DilumAluthge** [comment]
Bump. Can we merge this please? It will fix some issues in a PkgEval run that we are working on.

**Comment by sbromberger** [comment]
I just merged it since it seemed urgent. @simonschoelly - feel free to revert if necessary.

**Comment by KristofferC** [comment]
And a tag? :angel:

**Comment by sbromberger** [comment]
Ah. That'll have to wait for @simonschoelly, I'm afraid.

**Comment by DilumAluthge** [comment]
Anyone that's a member of the organization can make a release :)

**Comment by sbromberger** [comment]
Yes, but @simonschoelly is the _de facto_ custodian of this repo and there have been 9 other commits since the last release so I'm reluctant to do it without his review.

**Pull request merged**
