### PR TITLE
Add visual regression tests

### PR DESCRIPTION
**Pull request by juliohm**
Finally we have visual tests for GraphPlot.jl that doesn't require a human looking at the figures :blush:

### CODE REVIEW

**Comment by sbromberger** [comment]
https://travis-ci.org/JuliaGraphs/GraphPlot.jl/jobs/251609302#L361-L367

**Comment by juliohm** [comment]
Yes, I was just reading it, it is weird, never had that error using VisualRegressionTests.jl before. I will add these two packages as dependencies for the tests unless you know a format other than PNG that requires less dependencies...

**Comment by sbromberger** [comment]
Yeah, I think that's OK.

**Comment by juliohm** [comment]
Let's see if it works now...

**Comment by sbromberger** [comment]
This looks nasty: https://travis-ci.org/JuliaGraphs/GraphPlot.jl/jobs/251610987#L3294-L3300

**Comment by juliohm** [comment]
Yes, Julia v0.7 is crashing in all possible ways. We have it passing in Julia v0.6, I think we can merge it without problems?

**Comment by sbromberger** [comment]
Let's change nightly tests so that they don't cause a failure. One sec.

**Comment by sbromberger** [comment]
@afternone - do you have any objection to me merging PRs in your package?

**Comment by afternone** [comment]
@sbromberger Please merge them. Thanks!

**Comment by sbromberger** [comment]
Thanks, @afternone.

Nice work, @juliohm!

**Pull request merged**
