### PR TITLE
fixes #59

### LINKED ISSUE #59: gplot throws an InexactError() exception when the input x and y locations are integers
It looks like the signature for `gplot` indicates that the `x_loc_in` and `y_loc_in` arguments can be any subtype of `Real`, but when I input integer arrays for those arguments, an `InexactError()` is thrown:

```julia
grid = Grid([4, 8])
xloc = repeat(collect(1:8); inner = 4)
yloc = repeat(collect(1:4); outer = 8)
gplot(grid, xloc, yloc)
```

> ERROR: InexactError()
Stacktrace:
 [1] convert(::Type{Int64}, ::Float64) at ./float.jl:679
 [2] map!(::GraphPlot.##29#34, ::Array{Int64,1}, ::Array{Int64,1}) at ./abstractarray.jl:1862
 [3] #gplot#28(::Void, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Any,1}, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::Float64, ::Float64, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::Void, ::Float64, ::Float64, ::Float64, ::String, ::Float64, ::GraphPlot.#gplot, ::LightGraphs.SimpleGraphs.SimpleGraph{Int64}, ::Array{Int64,1}, ::Array{Int64,1}) at /home/cbieganek/.julia/v0.6/GraphPlot/src/plot.jl:134
 [4] gplot(::LightGraphs.SimpleGraphs.SimpleGraph{Int64}, ::Array{Int64,1}, ::Array{Int64,1}) at /home/cbieganek/.julia/v0.6/GraphPlot/src/plot.jl:115

It works fine if I input arrays of floats instead:

```julia
gplot(grid, Float64.(xloc), Float64.(yloc))
```

### PR DESCRIPTION
**Pull request by sbromberger**
Fixes #59 and provides minor optimizations.

### CODE REVIEW

**Comment by sbromberger** [comment]
Failures are for dependencies on -nightly. @afternone / @juliohm  - could you please review this and let me know if it's ok?

**Comment by juliohm** [comment]
Thank you @sbromberger for the fixes. The all look fine to me, could you please confirm that replacing `deepcopy` in those two lines has no side effects? Feel free to merge anytime after @afternone's feedback.

**Comment by sbromberger** [comment]
> could you please confirm that replacing deepcopy in those two lines has no side effects?

It shouldn't. The deepcopy was of vectors; creating a new vector that casts them explicitly to `Float64` should have the same effect (as well as preventing the `InexactError`).

**Comment by sbromberger** [comment]
Also, I haven't seen @afternone in a while, and his github account appears to be idle since at least the beginning of this year!

**Comment by juliohm** [comment]
True! I don't hear from him in a while. Maybe we should merge the PR if he doesn't reply in the following days.

**Pull request merged**
